package co.hoppen.filterlib;

/**
 * Created by YangJianHui on 2021/9/10.
 */
public enum FilterType {
    SKIN_HYDRATION_STATUS,
    SKIN_OIL_SECRETION,
    SKIN_PIGMENT_STATUS,
    SKIN_RED_BLOOD_STATUS,
    FOLLICLE_CLEAN_DEGREE,
    ELASTIC_FIBER_STATUS,
    COLLAGEN_STATUS,

    FACE_HYDRATION_STATUS,
    FACE_OIL_SECRETION,
    FACE_SKIN_EPIDERMIS_SPOTS,

    FACE_SKIN_WRINKLE,
    TEST
}
